/**
 * Classical Vedic Transit (Gochar) Constants & Interpretation Matrix
 * Based on Brihat Samhita, Phaladeepika, and Jataka Parijata.
 */

// 1. Auspicious (Subha) Transit Houses from Janma Rashi (Natal Moon)
export const FAVORABLE_GOCHAR_HOUSES: Record<string, number[]> = {
  Sun: [3, 6, 10, 11],
  Moon: [1, 3, 6, 7, 10, 11],
  Mars: [3, 6, 11],
  Mercury: [2, 4, 6, 8, 10, 11],
  Jupiter: [2, 5, 7, 9, 11],
  Venus: [1, 2, 3, 4, 5, 8, 9, 11, 12],
  Saturn: [3, 6, 11],
  Rahu: [3, 6, 10, 11],
  Ketu: [3, 6, 11],
};

// 2. Classical Vedha (Obstruction) Table:
// When a planet transits an auspicious house, its fruit is obstructed if another planet
// occupies its corresponding Vedha house from Janma Rashi.
export const VEDHA_PAIRS: Record<string, Record<number, number>> = {
  Sun: {
    3: 9,
    6: 12,
    10: 4,
    11: 5,
  },
  Moon: {
    1: 5,
    3: 9,
    6: 12,
    7: 2,
    10: 4,
    11: 8,
  },
  Mars: {
    3: 12,
    6: 9,
    11: 5,
  },
  Mercury: {
    2: 5,
    4: 3,
    6: 9,
    8: 1,
    10: 7,
    11: 12,
  },
  Jupiter: {
    2: 12,
    5: 4,
    7: 3,
    9: 10,
    11: 8,
  },
  Venus: {
    1: 8,
    2: 7,
    3: 1,
    4: 10,
    5: 9,
    8: 5,
    9: 11,
    11: 6,
    12: 3,
  },
  Saturn: {
    3: 12,
    6: 9,
    11: 5,
  },
  Rahu: {
    3: 12,
    6: 9,
    10: 4,
    11: 5,
  },
  Ketu: {
    3: 12,
    6: 9,
    11: 5,
  },
};

// 3. Shastric Vedha Exemptions:
// - Sun and Saturn (Father and Son) do not cause mutual Vedha.
// - Moon and Mercury do not cause mutual Vedha.
export const VEDHA_EXEMPTIONS: Array<{ planetA: string; planetB: string }> = [
  { planetA: "Sun", planetB: "Saturn" },
  { planetA: "Saturn", planetB: "Sun" },
  { planetA: "Moon", planetB: "Mercury" },
  { planetA: "Mercury", planetB: "Moon" },
];

// 4. Classical Gochar Predictions (Houses 1 to 12 from Janma Rashi)
export const PLANET_GOCHAR_PHALA: Record<string, Record<number, { isFavorable: boolean; description: string }>> = {
  Sun: {
    1: { isFavorable: false, description: "Fatigue, irritability, high expenditure, and eye/head heat." },
    2: { isFavorable: false, description: "Financial strain, disputes over possessions, harsh speech." },
    3: { isFavorable: true, description: "Courage, victory over opposition, official favor, and prestige." },
    4: { isFavorable: false, description: "Domestic restlessness, mental worry, maternal concerns." },
    5: { isFavorable: false, description: "Intellectual anxiety, speculation risks, tension regarding children." },
    6: { isFavorable: true, description: "Destruction of rivals, radiant health, debt clearance, and success." },
    7: { isFavorable: false, description: "Strained partnerships, public friction, tedious travels." },
    8: { isFavorable: false, description: "Sudden obstacles, low vitality, regulatory scrutiny." },
    9: { isFavorable: false, description: "Disagreements with seniors, delayed fortunes, ethical trials." },
    10: { isFavorable: true, description: "Career advancement, executive recognition, fulfillment of targets." },
    11: { isFavorable: true, description: "Substantial profits, influential friendships, honor, and prosperity." },
    12: { isFavorable: false, description: "Heavy outlays, sleep disturbances, isolation, travel expenses." },
  },
  Moon: {
    1: { isFavorable: true, description: "Mental freshness, culinary comforts, social appeal, and sound health." },
    2: { isFavorable: false, description: "Financial fluctuations, momentary gloom, speech misunderstandings." },
    3: { isFavorable: true, description: "Cheerful mind, courageous enterprise, joyful sibling ties, gains." },
    4: { isFavorable: false, description: "Emotional insecurity, domestic turbulence, disturbed peace of mind." },
    5: { isFavorable: false, description: "Scattered focus, emotional restlessness, disappointment in romance." },
    6: { isFavorable: true, description: "Relief from ailments, triumph over adversaries, debt settlement." },
    7: { isFavorable: true, description: "Harmonious marital exchange, romantic delight, successful partnerships." },
    8: { isFavorable: false, description: "Chandrashtama: heightened emotional sensitivity, anxiety, caution needed." },
    9: { isFavorable: false, description: "Spiritual restlessness, fatigue from travels, delayed fortune." },
    10: { isFavorable: true, description: "Professional accomplishment, public goodwill, decisive authority." },
    11: { isFavorable: true, description: "Abundant domestic joy, income gains, fulfillment of immediate wishes." },
    12: { isFavorable: false, description: "Extravagance, insomnia, emotional drain, and aimless wandering." },
  },
  Mars: {
    1: { isFavorable: false, description: "Impulsiveness, bodily injuries or heat, aggressive interpersonal friction." },
    2: { isFavorable: false, description: "Financial volatility, harsh words, sudden arguments in household." },
    3: { isFavorable: true, description: "Fearless valor, conquest of challenges, initiative, material acquisition." },
    4: { isFavorable: false, description: "Property disputes, domestic conflict, unrest within family." },
    5: { isFavorable: false, description: "Loss of temper, speculation losses, friction with romantic interests." },
    6: { isFavorable: true, description: "Crushing defeat of enemies, vitality, legal triumph, career gains." },
    7: { isFavorable: false, description: "Marital disharmony, discord with associates, bilateral clashes." },
    8: { isFavorable: false, description: "Accident vulnerability, surgical indications, sudden financial shocks." },
    9: { isFavorable: false, description: "Ideological clashes with elders, fruitless journeys, loss of momentum." },
    10: { isFavorable: false, description: "Professional friction with superiors, high stress, excessive workload." },
    11: { isFavorable: true, description: "Substantial financial influx, real-estate success, victory, dynamic leadership." },
    12: { isFavorable: false, description: "Unforeseen liabilities, physical weariness, legal penalties." },
  },
  Mercury: {
    1: { isFavorable: false, description: "Cerebral overload, deceit from associates, nervousness." },
    2: { isFavorable: true, description: "Financial inflows, persuasive eloquence, scholarly acquisition, respect." },
    3: { isFavorable: false, description: "Communication mishaps, friction with siblings, contractual setbacks." },
    4: { isFavorable: true, description: "Domestic learning, acquisition of intellectual tools, family affection." },
    5: { isFavorable: false, description: "Wavering discernment, speculative risks, mental dispersion." },
    6: { isFavorable: true, description: "Intellectual supremacy over rivals, analytical mastery, career applause." },
    7: { isFavorable: false, description: "Bickering in partnerships, commercial contractual misunderstandings." },
    8: { isFavorable: true, description: "Unexpected financial gains, psychological acumen, victory in disputes." },
    9: { isFavorable: false, description: "Obstacles in higher education, delay in publications, philosophical doubts." },
    10: { isFavorable: true, description: "Career growth, high business acumen, trade prosperity, public acclaim." },
    11: { isFavorable: true, description: "Profitable networking, commercial windfalls, delightful social connections." },
    12: { isFavorable: false, description: "Auditing troubles, document misplacement, wasted expenses." },
  },
  Jupiter: {
    1: { isFavorable: false, description: "Loss of judgment through overconfidence, relocation strain, financial overheads." },
    2: { isFavorable: true, description: "Abundant wealth accumulation, sweet family speech, matrimonial joy, respect." },
    3: { isFavorable: false, description: "Stagnation in endeavors, lack of mentor support, sibling friction." },
    4: { isFavorable: false, description: "Domestic upheaval, property worries, sorrow regarding relatives." },
    5: { isFavorable: true, description: "Profound wisdom, child blessings, romantic joy, divine grace, investment boom." },
    6: { isFavorable: false, description: "Opponents gain ground, digestive sluggishness, workplace politics." },
    7: { isFavorable: true, description: "Splendid matrimonial bliss, lucrative partnerships, social elevation, travel." },
    8: { isFavorable: false, description: "Fatigue, travel fatigue, legal delays, reduced spiritual focus." },
    9: { isFavorable: true, description: "Supreme luck (Bhagya-Udaya), paternal blessings, spiritual pilgrimage, victory." },
    10: { isFavorable: false, description: "Demanding professional transitions, loss of ease, high administrative load." },
    11: { isFavorable: true, description: "Realization of major ambitions, high wealth flow, auspicious celebrations." },
    12: { isFavorable: false, description: "Heavy philanthropic expenditure, philosophical isolation, wanderlust." },
  },
  Venus: {
    1: { isFavorable: true, description: "Sensory delight, charming demeanor, luxury purchases, romantic warmth." },
    2: { isFavorable: true, description: "Financial prosperity, jewels and ornaments, sweet harmony at home." },
    3: { isFavorable: true, description: "Artistic creativity, delightful travels, influential allies, popularity." },
    4: { isFavorable: true, description: "Vehicle purchases, home beautification, luxury living, maternal affection." },
    5: { isFavorable: true, description: "Joyful romance, artistic recognition, entertainment, happiness through children." },
    6: { isFavorable: false, description: "Rivalry, romantic misunderstandings, urinary or kidney sensitivity." },
    7: { isFavorable: false, description: "Ego clashes with spouse, excessive expenditure on indulgence, scandals." },
    8: { isFavorable: true, description: "Sudden luxury gains, sensual pleasures, inheritance or partner's money." },
    9: { isFavorable: true, description: "Virtuous deeds, cultural travel, graceful social standing, prosperity." },
    10: { isFavorable: false, description: "Workplace aesthetic disagreements, reputational sensitivity, lethargy." },
    11: { isFavorable: true, description: "Massive financial rewards, elite social circles, romantic fulfillment." },
    12: { isFavorable: true, description: "Bed comforts, opulent spending, overseas pleasure, artistic solitude." },
  },
  Saturn: {
    1: { isFavorable: false, description: "Sade Sati Peak: severe mental pressure, heavy burdens, delayed progress." },
    2: { isFavorable: false, description: "Sade Sati Setting: financial consolidation, family obligations, strict discipline." },
    3: { isFavorable: true, description: "Immense resilience, decisive victory, organizational mastery, new enterprise." },
    4: { isFavorable: false, description: "Dhaiya (Kantaka Shani): domestic melancholy, property encumbrance, maternal health." },
    5: { isFavorable: false, description: "Intellectual exhaustion, speculative losses, strain in romantic commitments." },
    6: { isFavorable: true, description: "Complete annihilation of debts and enemies, rugged stamina, career rise." },
    7: { isFavorable: false, description: "Heavy marital duties, distance in partnerships, protracted negotiations." },
    8: { isFavorable: false, description: "Ashtama Shani: acute transformation, obstacles, career hurdles, health vigilance." },
    9: { isFavorable: false, description: "Father's health concerns, ideological questioning, delayed divine favors." },
    10: { isFavorable: false, description: "Overwhelming professional responsibilities, public scrutiny, test of endurance." },
    11: { isFavorable: true, description: "Permanent wealth building, high long-term gains, influential elder allies." },
    12: { isFavorable: false, description: "Sade Sati Rising: escalating expenses, insomnia, foreign residence challenges." },
  },
  Rahu: {
    1: { isFavorable: false, description: "Mental confusion, illusory desires, impulsive shifts in identity." },
    2: { isFavorable: false, description: "Sudden financial drain, sharp speech, eating irregularities." },
    3: { isFavorable: true, description: "Fearless audacity, unconventional success, digital/media expansion, gains." },
    4: { isFavorable: false, description: "Domestic insecurity, shifting residence, discord with relatives." },
    5: { isFavorable: false, description: "Speculative illusions, restlessness, tension in child affairs." },
    6: { isFavorable: true, description: "Total dominance over competitors, strategic victory, immune resilience." },
    7: { isFavorable: false, description: "Marital suspicion, unusual partner demands, foreign entanglements." },
    8: { isFavorable: false, description: "Mysterious ailments, phobias, unexpected financial disruptions." },
    9: { isFavorable: false, description: "Unorthodox views, alienation from ancestral traditions, travel fatigue." },
    10: { isFavorable: true, description: "Skyrocketing ambition, political or executive breakthrough, modern enterprise." },
    11: { isFavorable: true, description: "Huge unconventional windfalls, expansive foreign networks, fulfillment." },
    12: { isFavorable: false, description: "Exorbitant wasteful expenses, sleep disturbances, exile or seclusion." },
  },
  Ketu: {
    1: { isFavorable: false, description: "Identity detachment, aimless introspection, low physical vigor." },
    2: { isFavorable: false, description: "Detachment from family wealth, cryptic speech, mouth/teeth sensitivity." },
    3: { isFavorable: true, description: "Courageous independence, spiritual valor, elimination of trivial fears." },
    4: { isFavorable: false, description: "Disconnection from domestic comfort, spiritual wandering, maternal worries." },
    5: { isFavorable: false, description: "Detached intellect, mantra sadhana, friction in romantic attachments." },
    6: { isFavorable: true, description: "Spiritual protection against foes, overcoming hidden diseases, ascetic strength." },
    7: { isFavorable: false, description: "Emotional detachment in marriage, aloof partner demeanor, misunderstandings." },
    8: { isFavorable: false, description: "Occult interest, unexpected health anomalies, isolation." },
    9: { isFavorable: false, description: "Rejection of dogmas, solitary pilgrimage, ideological isolation." },
    10: { isFavorable: false, description: "Career disillusionment, desire to quit corporate grind, ascetic tendencies." },
    11: { isFavorable: true, description: "Detached yet abundant financial inflows, spiritual gains, liberation." },
    12: { isFavorable: false, description: "Moksha orientation, heavy expenses on spirituality, foreign isolation." },
  },
};
